AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function with IAM role and S3 trigger (prefix filter)

Resources:
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: my-lambda-learning-function
      Runtime: python3.12
      Handler: main.lambda_handler
      Role: !GetAtt MyLambdaRole.Arn
      Code:
        S3Bucket: my-s3-bucket-us-east-1-042470866308   # <-- hard-coded bucket name
        S3Key: artifacts/my-lambda.zip

  MyBucketNotification:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: my-s3-bucket-us-east-1-042470866308       # <-- same hard-coded bucket name
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Function: !GetAtt MyLambdaFunction.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: inbound/
    DependsOn: MyLambdaPermission

  MyLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref MyLambdaFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::my-s3-bucket-us-east-1-042470866308
