name: Deploy Lambda with S3 Trigger

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region to deploy"
        required: true
        default: us-east-1
        type: choice
        options:
          - us-east-1
          - us-west-2
          - ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt -t src/

      - name: Zip Lambda package
        run: |
          cd src
          zip -r ../my-lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region || 'us-east-1' }}

      - name: Upload to S3
        run: aws s3 cp my-lambda.zip s3://my-s3-bucket-us-east-1-042470866308/artifacts/

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file lambda.yml \
            --stack-name my-lambda-stack \
            --capabilities CAPABILITY_IAM \
            --region ${{ github.event.inputs.region || 'us-east-1' }}
